apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ebpf-poc-ingress
  namespace: ebpf-poc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ebpf-poc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java8-gateway
            port:
              number: 8080
